# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
name: wazuh-remote

x-logging: &default-logging
  driver: local
  options:
    max-size: ${DOCKER_LOG_MAX_SIZE:-50m}
    max-file: ${DOCKER_LOG_MAX_FILE:-7}

services:
  wazuh.agent:
    image: wazuh/wazuh-agent:${WAZUH_STACK_VERSION:-4.14.5}
    container_name: wazuh-remote-agent
    restart: always
    logging: *default-logging
    env_file:
      - .env
    environment:
      - WAZUH_MANAGER_SERVER=${WAZUH_MANAGER_SERVER}
      - WAZUH_REGISTRATION_SERVER=${WAZUH_REGISTRATION_SERVER:-${WAZUH_MANAGER_SERVER}}
      - WAZUH_AGENT_GROUP=${WAZUH_AGENT_GROUP:-default}
      - WAZUH_AGENT_NAME=${WAZUH_AGENT_NAME:-wazuh-docker-agent}
    volumes:
      - wazuh-agent-etc:/var/ossec/etc
      - ./config/wazuh-agent-conf:/wazuh-config-mount/etc/ossec.conf

volumes:
  wazuh-agent-etc:
